// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/attr_value.proto

package org.tensorflow.framework;

public interface AttrValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.AttrValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes s = 2;</code>
   *
   * <pre>
   * "string"
   * </pre>
   */
  com.google.protobuf.ByteString getS();

  /**
   * <code>optional int64 i = 3;</code>
   *
   * <pre>
   * "int"
   * </pre>
   */
  long getI();

  /**
   * <code>optional float f = 4;</code>
   *
   * <pre>
   * "float"
   * </pre>
   */
  float getF();

  /**
   * <code>optional bool b = 5;</code>
   *
   * <pre>
   * "bool"
   * </pre>
   */
  boolean getB();

  /**
   * <code>optional .tensorflow.DataType type = 6;</code>
   *
   * <pre>
   * "type"
   * </pre>
   */
  int getTypeValue();
  /**
   * <code>optional .tensorflow.DataType type = 6;</code>
   *
   * <pre>
   * "type"
   * </pre>
   */
  org.tensorflow.framework.DataType getType();

  /**
   * <code>optional .tensorflow.TensorShapeProto shape = 7;</code>
   *
   * <pre>
   * "shape"
   * </pre>
   */
  org.tensorflow.framework.TensorShapeProto getShape();
  /**
   * <code>optional .tensorflow.TensorShapeProto shape = 7;</code>
   *
   * <pre>
   * "shape"
   * </pre>
   */
  org.tensorflow.framework.TensorShapeProtoOrBuilder getShapeOrBuilder();

  /**
   * <code>optional .tensorflow.TensorProto tensor = 8;</code>
   *
   * <pre>
   * "tensor"
   * </pre>
   */
  org.tensorflow.framework.TensorProto getTensor();
  /**
   * <code>optional .tensorflow.TensorProto tensor = 8;</code>
   *
   * <pre>
   * "tensor"
   * </pre>
   */
  org.tensorflow.framework.TensorProtoOrBuilder getTensorOrBuilder();

  /**
   * <code>optional .tensorflow.AttrValue.ListValue list = 1;</code>
   *
   * <pre>
   * any "list(...)"
   * </pre>
   */
  org.tensorflow.framework.AttrValue.ListValue getList();
  /**
   * <code>optional .tensorflow.AttrValue.ListValue list = 1;</code>
   *
   * <pre>
   * any "list(...)"
   * </pre>
   */
  org.tensorflow.framework.AttrValue.ListValueOrBuilder getListOrBuilder();

  /**
   * <code>optional .tensorflow.NameAttrList func = 10;</code>
   *
   * <pre>
   * "func" represents a function. func.name is a function's name or
   * a primitive op's name. func.attr.first is the name of an attr
   * defined for that function. func.attr.second is the value for
   * that attr in the instantiation.
   * </pre>
   */
  org.tensorflow.framework.NameAttrList getFunc();
  /**
   * <code>optional .tensorflow.NameAttrList func = 10;</code>
   *
   * <pre>
   * "func" represents a function. func.name is a function's name or
   * a primitive op's name. func.attr.first is the name of an attr
   * defined for that function. func.attr.second is the value for
   * that attr in the instantiation.
   * </pre>
   */
  org.tensorflow.framework.NameAttrListOrBuilder getFuncOrBuilder();

  /**
   * <code>optional string placeholder = 9;</code>
   *
   * <pre>
   * This is a placeholder only used in nodes defined inside a
   * function.  It indicates the attr value will be supplied when
   * the function is instantiated.  For example, let us suppose a
   * node "N" in function "FN". "N" has an attr "A" with value
   * placeholder = "foo". When FN is instantiated with attr "foo"
   * set to "bar", the instantiated node N's attr A will have been
   * given the value "bar".
   * </pre>
   */
  java.lang.String getPlaceholder();
  /**
   * <code>optional string placeholder = 9;</code>
   *
   * <pre>
   * This is a placeholder only used in nodes defined inside a
   * function.  It indicates the attr value will be supplied when
   * the function is instantiated.  For example, let us suppose a
   * node "N" in function "FN". "N" has an attr "A" with value
   * placeholder = "foo". When FN is instantiated with attr "foo"
   * set to "bar", the instantiated node N's attr A will have been
   * given the value "bar".
   * </pre>
   */
  com.google.protobuf.ByteString
      getPlaceholderBytes();

  public org.tensorflow.framework.AttrValue.ValueCase getValueCase();
}
