// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/config.proto

package org.tensorflow.framework;

public final class ConfigProtos {
  private ConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GPUOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_GPUOptions_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_OptimizerOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_OptimizerOptions_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GraphOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_GraphOptions_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ConfigProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_ConfigProto_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ConfigProto_DeviceCountEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_ConfigProto_DeviceCountEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&tensorflow/core/framework/config.proto" +
      "\022\ntensorflow\"n\n\nGPUOptions\022\'\n\037per_proces" +
      "s_gpu_memory_fraction\030\001 \001(\001\022\026\n\016allocator" +
      "_type\030\002 \001(\t\022\037\n\027deferred_deletion_bytes\030\003" +
      " \001(\003\"\333\001\n\020OptimizerOptions\022+\n#do_common_s" +
      "ubexpression_elimination\030\001 \001(\010\022\033\n\023do_con" +
      "stant_folding\030\002 \001(\010\022\034\n\024do_function_inlin" +
      "ing\030\004 \001(\010\0225\n\topt_level\030\003 \001(\0162\".tensorflo" +
      "w.OptimizerOptions.Level\"(\n\005Level\022\006\n\002L1\020" +
      "\000\022\006\n\002L2\020\002\022\017\n\002L0\020\377\377\377\377\377\377\377\377\377\001\"\224\001\n\014GraphOpti",
      "ons\022\036\n\026enable_recv_scheduling\030\002 \001(\010\0227\n\021o" +
      "ptimizer_options\030\003 \001(\0132\034.tensorflow.Opti" +
      "mizerOptionsJ\004\010\001\020\002R%skip_common_subexpre" +
      "ssion_elimination\"\272\003\n\013ConfigProto\022>\n\014dev" +
      "ice_count\030\001 \003(\0132(.tensorflow.ConfigProto" +
      ".DeviceCountEntry\022$\n\034intra_op_parallelis" +
      "m_threads\030\002 \001(\005\022$\n\034inter_op_parallelism_" +
      "threads\030\005 \001(\005\022\037\n\027use_per_session_threads" +
      "\030\t \001(\010\022\030\n\020placement_period\030\003 \001(\005\022\026\n\016devi" +
      "ce_filters\030\004 \003(\t\022+\n\013gpu_options\030\006 \001(\0132\026.",
      "tensorflow.GPUOptions\022\034\n\024allow_soft_plac" +
      "ement\030\007 \001(\010\022\034\n\024log_device_placement\030\010 \001(" +
      "\010\022/\n\rgraph_options\030\n \001(\0132\030.tensorflow.Gr" +
      "aphOptions\0322\n\020DeviceCountEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\005:\0028\001B*\n\030org.tensorflow" +
      ".frameworkB\014ConfigProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_GPUOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_GPUOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_GPUOptions_descriptor,
        new java.lang.String[] { "PerProcessGpuMemoryFraction", "AllocatorType", "DeferredDeletionBytes", });
    internal_static_tensorflow_OptimizerOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_OptimizerOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_OptimizerOptions_descriptor,
        new java.lang.String[] { "DoCommonSubexpressionElimination", "DoConstantFolding", "DoFunctionInlining", "OptLevel", });
    internal_static_tensorflow_GraphOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_GraphOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_GraphOptions_descriptor,
        new java.lang.String[] { "EnableRecvScheduling", "OptimizerOptions", });
    internal_static_tensorflow_ConfigProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_ConfigProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_ConfigProto_descriptor,
        new java.lang.String[] { "DeviceCount", "IntraOpParallelismThreads", "InterOpParallelismThreads", "UsePerSessionThreads", "PlacementPeriod", "DeviceFilters", "GpuOptions", "AllowSoftPlacement", "LogDevicePlacement", "GraphOptions", });
    internal_static_tensorflow_ConfigProto_DeviceCountEntry_descriptor =
      internal_static_tensorflow_ConfigProto_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_ConfigProto_DeviceCountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_ConfigProto_DeviceCountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
