// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/types.proto

package org.tensorflow.framework;

/**
 * Protobuf enum {@code tensorflow.DataType}
 */
public enum DataType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DT_INVALID = 0;</code>
   *
   * <pre>
   * Not a legal value for DataType.  Used to indicate a DataType field
   * has not been set.
   * </pre>
   */
  DT_INVALID(0, 0),
  /**
   * <code>DT_FLOAT = 1;</code>
   *
   * <pre>
   * Data types that all computation devices are expected to be
   * capable to support.
   * </pre>
   */
  DT_FLOAT(1, 1),
  /**
   * <code>DT_DOUBLE = 2;</code>
   */
  DT_DOUBLE(2, 2),
  /**
   * <code>DT_INT32 = 3;</code>
   */
  DT_INT32(3, 3),
  /**
   * <code>DT_UINT8 = 4;</code>
   */
  DT_UINT8(4, 4),
  /**
   * <code>DT_INT16 = 5;</code>
   */
  DT_INT16(5, 5),
  /**
   * <code>DT_INT8 = 6;</code>
   */
  DT_INT8(6, 6),
  /**
   * <code>DT_STRING = 7;</code>
   */
  DT_STRING(7, 7),
  /**
   * <code>DT_COMPLEX64 = 8;</code>
   *
   * <pre>
   * Single-precision complex
   * </pre>
   */
  DT_COMPLEX64(8, 8),
  /**
   * <code>DT_INT64 = 9;</code>
   */
  DT_INT64(9, 9),
  /**
   * <code>DT_BOOL = 10;</code>
   */
  DT_BOOL(10, 10),
  /**
   * <code>DT_QINT8 = 11;</code>
   *
   * <pre>
   * Quantized int8
   * </pre>
   */
  DT_QINT8(11, 11),
  /**
   * <code>DT_QUINT8 = 12;</code>
   *
   * <pre>
   * Quantized uint8
   * </pre>
   */
  DT_QUINT8(12, 12),
  /**
   * <code>DT_QINT32 = 13;</code>
   *
   * <pre>
   * Quantized int32
   * </pre>
   */
  DT_QINT32(13, 13),
  /**
   * <code>DT_BFLOAT16 = 14;</code>
   *
   * <pre>
   * Float32 truncated to 16 bits.  Only for cast ops.
   * </pre>
   */
  DT_BFLOAT16(14, 14),
  /**
   * <code>DT_QINT16 = 15;</code>
   *
   * <pre>
   * Quantized int16
   * </pre>
   */
  DT_QINT16(15, 15),
  /**
   * <code>DT_QUINT16 = 16;</code>
   *
   * <pre>
   * Quantized uint16
   * </pre>
   */
  DT_QUINT16(16, 16),
  /**
   * <code>DT_UINT16 = 17;</code>
   */
  DT_UINT16(17, 17),
  /**
   * <code>DT_FLOAT_REF = 101;</code>
   *
   * <pre>
   * Do not use!  These are only for parameters.  Every enum above
   * should have a corresponding value below (verified by types_test).
   * </pre>
   */
  DT_FLOAT_REF(18, 101),
  /**
   * <code>DT_DOUBLE_REF = 102;</code>
   */
  DT_DOUBLE_REF(19, 102),
  /**
   * <code>DT_INT32_REF = 103;</code>
   */
  DT_INT32_REF(20, 103),
  /**
   * <code>DT_UINT8_REF = 104;</code>
   */
  DT_UINT8_REF(21, 104),
  /**
   * <code>DT_INT16_REF = 105;</code>
   */
  DT_INT16_REF(22, 105),
  /**
   * <code>DT_INT8_REF = 106;</code>
   */
  DT_INT8_REF(23, 106),
  /**
   * <code>DT_STRING_REF = 107;</code>
   */
  DT_STRING_REF(24, 107),
  /**
   * <code>DT_COMPLEX64_REF = 108;</code>
   */
  DT_COMPLEX64_REF(25, 108),
  /**
   * <code>DT_INT64_REF = 109;</code>
   */
  DT_INT64_REF(26, 109),
  /**
   * <code>DT_BOOL_REF = 110;</code>
   */
  DT_BOOL_REF(27, 110),
  /**
   * <code>DT_QINT8_REF = 111;</code>
   */
  DT_QINT8_REF(28, 111),
  /**
   * <code>DT_QUINT8_REF = 112;</code>
   */
  DT_QUINT8_REF(29, 112),
  /**
   * <code>DT_QINT32_REF = 113;</code>
   */
  DT_QINT32_REF(30, 113),
  /**
   * <code>DT_BFLOAT16_REF = 114;</code>
   */
  DT_BFLOAT16_REF(31, 114),
  /**
   * <code>DT_QINT16_REF = 115;</code>
   */
  DT_QINT16_REF(32, 115),
  /**
   * <code>DT_QUINT16_REF = 116;</code>
   */
  DT_QUINT16_REF(33, 116),
  /**
   * <code>DT_UINT16_REF = 117;</code>
   */
  DT_UINT16_REF(34, 117),
  UNRECOGNIZED(-1, -1),
  ;

  /**
   * <code>DT_INVALID = 0;</code>
   *
   * <pre>
   * Not a legal value for DataType.  Used to indicate a DataType field
   * has not been set.
   * </pre>
   */
  public static final int DT_INVALID_VALUE = 0;
  /**
   * <code>DT_FLOAT = 1;</code>
   *
   * <pre>
   * Data types that all computation devices are expected to be
   * capable to support.
   * </pre>
   */
  public static final int DT_FLOAT_VALUE = 1;
  /**
   * <code>DT_DOUBLE = 2;</code>
   */
  public static final int DT_DOUBLE_VALUE = 2;
  /**
   * <code>DT_INT32 = 3;</code>
   */
  public static final int DT_INT32_VALUE = 3;
  /**
   * <code>DT_UINT8 = 4;</code>
   */
  public static final int DT_UINT8_VALUE = 4;
  /**
   * <code>DT_INT16 = 5;</code>
   */
  public static final int DT_INT16_VALUE = 5;
  /**
   * <code>DT_INT8 = 6;</code>
   */
  public static final int DT_INT8_VALUE = 6;
  /**
   * <code>DT_STRING = 7;</code>
   */
  public static final int DT_STRING_VALUE = 7;
  /**
   * <code>DT_COMPLEX64 = 8;</code>
   *
   * <pre>
   * Single-precision complex
   * </pre>
   */
  public static final int DT_COMPLEX64_VALUE = 8;
  /**
   * <code>DT_INT64 = 9;</code>
   */
  public static final int DT_INT64_VALUE = 9;
  /**
   * <code>DT_BOOL = 10;</code>
   */
  public static final int DT_BOOL_VALUE = 10;
  /**
   * <code>DT_QINT8 = 11;</code>
   *
   * <pre>
   * Quantized int8
   * </pre>
   */
  public static final int DT_QINT8_VALUE = 11;
  /**
   * <code>DT_QUINT8 = 12;</code>
   *
   * <pre>
   * Quantized uint8
   * </pre>
   */
  public static final int DT_QUINT8_VALUE = 12;
  /**
   * <code>DT_QINT32 = 13;</code>
   *
   * <pre>
   * Quantized int32
   * </pre>
   */
  public static final int DT_QINT32_VALUE = 13;
  /**
   * <code>DT_BFLOAT16 = 14;</code>
   *
   * <pre>
   * Float32 truncated to 16 bits.  Only for cast ops.
   * </pre>
   */
  public static final int DT_BFLOAT16_VALUE = 14;
  /**
   * <code>DT_QINT16 = 15;</code>
   *
   * <pre>
   * Quantized int16
   * </pre>
   */
  public static final int DT_QINT16_VALUE = 15;
  /**
   * <code>DT_QUINT16 = 16;</code>
   *
   * <pre>
   * Quantized uint16
   * </pre>
   */
  public static final int DT_QUINT16_VALUE = 16;
  /**
   * <code>DT_UINT16 = 17;</code>
   */
  public static final int DT_UINT16_VALUE = 17;
  /**
   * <code>DT_FLOAT_REF = 101;</code>
   *
   * <pre>
   * Do not use!  These are only for parameters.  Every enum above
   * should have a corresponding value below (verified by types_test).
   * </pre>
   */
  public static final int DT_FLOAT_REF_VALUE = 101;
  /**
   * <code>DT_DOUBLE_REF = 102;</code>
   */
  public static final int DT_DOUBLE_REF_VALUE = 102;
  /**
   * <code>DT_INT32_REF = 103;</code>
   */
  public static final int DT_INT32_REF_VALUE = 103;
  /**
   * <code>DT_UINT8_REF = 104;</code>
   */
  public static final int DT_UINT8_REF_VALUE = 104;
  /**
   * <code>DT_INT16_REF = 105;</code>
   */
  public static final int DT_INT16_REF_VALUE = 105;
  /**
   * <code>DT_INT8_REF = 106;</code>
   */
  public static final int DT_INT8_REF_VALUE = 106;
  /**
   * <code>DT_STRING_REF = 107;</code>
   */
  public static final int DT_STRING_REF_VALUE = 107;
  /**
   * <code>DT_COMPLEX64_REF = 108;</code>
   */
  public static final int DT_COMPLEX64_REF_VALUE = 108;
  /**
   * <code>DT_INT64_REF = 109;</code>
   */
  public static final int DT_INT64_REF_VALUE = 109;
  /**
   * <code>DT_BOOL_REF = 110;</code>
   */
  public static final int DT_BOOL_REF_VALUE = 110;
  /**
   * <code>DT_QINT8_REF = 111;</code>
   */
  public static final int DT_QINT8_REF_VALUE = 111;
  /**
   * <code>DT_QUINT8_REF = 112;</code>
   */
  public static final int DT_QUINT8_REF_VALUE = 112;
  /**
   * <code>DT_QINT32_REF = 113;</code>
   */
  public static final int DT_QINT32_REF_VALUE = 113;
  /**
   * <code>DT_BFLOAT16_REF = 114;</code>
   */
  public static final int DT_BFLOAT16_REF_VALUE = 114;
  /**
   * <code>DT_QINT16_REF = 115;</code>
   */
  public static final int DT_QINT16_REF_VALUE = 115;
  /**
   * <code>DT_QUINT16_REF = 116;</code>
   */
  public static final int DT_QUINT16_REF_VALUE = 116;
  /**
   * <code>DT_UINT16_REF = 117;</code>
   */
  public static final int DT_UINT16_REF_VALUE = 117;


  public final int getNumber() {
    if (index == -1) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  public static DataType valueOf(int value) {
    switch (value) {
      case 0: return DT_INVALID;
      case 1: return DT_FLOAT;
      case 2: return DT_DOUBLE;
      case 3: return DT_INT32;
      case 4: return DT_UINT8;
      case 5: return DT_INT16;
      case 6: return DT_INT8;
      case 7: return DT_STRING;
      case 8: return DT_COMPLEX64;
      case 9: return DT_INT64;
      case 10: return DT_BOOL;
      case 11: return DT_QINT8;
      case 12: return DT_QUINT8;
      case 13: return DT_QINT32;
      case 14: return DT_BFLOAT16;
      case 15: return DT_QINT16;
      case 16: return DT_QUINT16;
      case 17: return DT_UINT16;
      case 101: return DT_FLOAT_REF;
      case 102: return DT_DOUBLE_REF;
      case 103: return DT_INT32_REF;
      case 104: return DT_UINT8_REF;
      case 105: return DT_INT16_REF;
      case 106: return DT_INT8_REF;
      case 107: return DT_STRING_REF;
      case 108: return DT_COMPLEX64_REF;
      case 109: return DT_INT64_REF;
      case 110: return DT_BOOL_REF;
      case 111: return DT_QINT8_REF;
      case 112: return DT_QUINT8_REF;
      case 113: return DT_QINT32_REF;
      case 114: return DT_BFLOAT16_REF;
      case 115: return DT_QINT16_REF;
      case 116: return DT_QUINT16_REF;
      case 117: return DT_UINT16_REF;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DataType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
          public DataType findValueByNumber(int number) {
            return DataType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.tensorflow.framework.TypesProtos.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final DataType[] VALUES = values();

  public static DataType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private DataType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tensorflow.DataType)
}

