// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/function.proto

package org.tensorflow.framework;

public interface FunctionDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.FunctionDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  boolean hasSignature();
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  org.tensorflow.framework.OpDef getSignature();
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  org.tensorflow.framework.OpDefOrBuilder getSignatureOrBuilder();

  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  java.util.List<org.tensorflow.framework.FunctionDef.Node> 
      getNodeList();
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  org.tensorflow.framework.FunctionDef.Node getNode(int index);
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  int getNodeCount();
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  java.util.List<? extends org.tensorflow.framework.FunctionDef.NodeOrBuilder> 
      getNodeOrBuilderList();
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  org.tensorflow.framework.FunctionDef.NodeOrBuilder getNodeOrBuilder(
      int index);
}
