// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/function.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.FunctionDef}
 *
 * <pre>
 * A function can be instantiated when the runtime can bind every attr
 * with a value. When a GraphDef has a call to a function, it must
 * have binding for every attr defined in the signature.
 * TODO(zhifengc):
 *   * device spec, etc.
 * </pre>
 */
public  final class FunctionDef extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tensorflow.FunctionDef)
    FunctionDefOrBuilder {
  // Use FunctionDef.newBuilder() to construct.
  private FunctionDef(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FunctionDef() {
    node_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FunctionDef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.tensorflow.framework.OpDef.Builder subBuilder = null;
            if (signature_ != null) {
              subBuilder = signature_.toBuilder();
            }
            signature_ = input.readMessage(org.tensorflow.framework.OpDef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(signature_);
              signature_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              node_ = new java.util.ArrayList<org.tensorflow.framework.FunctionDef.Node>();
              mutable_bitField0_ |= 0x00000002;
            }
            node_.add(input.readMessage(org.tensorflow.framework.FunctionDef.Node.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        node_ = java.util.Collections.unmodifiableList(node_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.FunctionDef.class, org.tensorflow.framework.FunctionDef.Builder.class);
  }

  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.FunctionDef.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getRetList();
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    int getRetCount();
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    java.lang.String getRet(int index);
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    com.google.protobuf.ByteString
        getRetBytes(int index);

    /**
     * <code>optional string op = 2;</code>
     *
     * <pre>
     * The op/function name.
     * </pre>
     */
    java.lang.String getOp();
    /**
     * <code>optional string op = 2;</code>
     *
     * <pre>
     * The op/function name.
     * </pre>
     */
    com.google.protobuf.ByteString
        getOpBytes();

    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getArgList();
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    int getArgCount();
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    java.lang.String getArg(int index);
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    com.google.protobuf.ByteString
        getArgBytes(int index);

    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getDepList();
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    int getDepCount();
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    java.lang.String getDep(int index);
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    com.google.protobuf.ByteString
        getDepBytes(int index);

    /**
     * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
     *
     * <pre>
     * Attrs.
     * 'attr' maps names defined by 'func's attr defs to attr values.
     * attr values may have placeholders which are substituted
     * recursively by concrete values when this node is instantiated.
     * These placeholders must name an attr listed in the FunctionDef's
     * signature.
     * </pre>
     */
    java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue>
    getAttr();
  }
  /**
   * Protobuf type {@code tensorflow.FunctionDef.Node}
   *
   * <pre>
   * A node is a multi-value assignment:
   *   (ret[0], ret[1], ...) = func(arg[0], arg[1], ...)
   * By convention, "func" is resolved by consulting with a user-defined
   * library first. If not resolved, "func" is assumed to be a builtin op.
   * </pre>
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.FunctionDef.Node)
      NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      ret_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      op_ = "";
      arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dep_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ret_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              ret_.add(s);
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              op_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                arg_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              arg_.add(s);
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                dep_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              dep_.add(s);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                attr_ = com.google.protobuf.MapField.newMapField(
                    AttrDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.framework.AttrValue>
              attr = input.readMessage(
                  AttrDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attr_.getMutableMap().put(attr.getKey(), attr.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ret_ = ret_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          arg_ = arg_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          dep_ = dep_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_Node_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAttr();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.FunctionDef.Node.class, org.tensorflow.framework.FunctionDef.Node.Builder.class);
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList ret_;
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getRetList() {
      return ret_;
    }
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    public int getRetCount() {
      return ret_.size();
    }
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    public java.lang.String getRet(int index) {
      return ret_.get(index);
    }
    /**
     * <code>repeated string ret = 1;</code>
     *
     * <pre>
     * This node produces multiple outputs. They are named ret[0],
     * ret[1], ..., etc.
     * REQUIRES: function.node.ret[*] are unique across all nodes.
     * REQUIRES: ret.size == func/op def's number of output args.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRetBytes(int index) {
      return ret_.getByteString(index);
    }

    public static final int OP_FIELD_NUMBER = 2;
    private volatile java.lang.Object op_;
    /**
     * <code>optional string op = 2;</code>
     *
     * <pre>
     * The op/function name.
     * </pre>
     */
    public java.lang.String getOp() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        op_ = s;
        return s;
      }
    }
    /**
     * <code>optional string op = 2;</code>
     *
     * <pre>
     * The op/function name.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOpBytes() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        op_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARG_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList arg_;
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getArgList() {
      return arg_;
    }
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    public int getArgCount() {
      return arg_.size();
    }
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    public java.lang.String getArg(int index) {
      return arg_.get(index);
    }
    /**
     * <code>repeated string arg = 3;</code>
     *
     * <pre>
     * Arguments passed to this func/op.
     * arg[i] must be either one of
     * function.signature.input_args[*].name or one of
     * function.node[*].ret[*].
     * REQUIRES: arg.size == func/op def's number of input args.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getArgBytes(int index) {
      return arg_.getByteString(index);
    }

    public static final int DEP_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList dep_;
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getDepList() {
      return dep_;
    }
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    public int getDepCount() {
      return dep_.size();
    }
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    public java.lang.String getDep(int index) {
      return dep_.get(index);
    }
    /**
     * <code>repeated string dep = 4;</code>
     *
     * <pre>
     * Control dependencies.
     * dep[i] must be one of function.node[*].ret[*] or one of
     * function.signature.input_args[*].name.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDepBytes(int index) {
      return dep_.getByteString(index);
    }

    public static final int ATTR_FIELD_NUMBER = 5;
    private static final class AttrDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, org.tensorflow.framework.AttrValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, org.tensorflow.framework.AttrValue>newDefaultInstance(
                  org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_Node_AttrEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  org.tensorflow.framework.AttrValue.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, org.tensorflow.framework.AttrValue> attr_;
    private com.google.protobuf.MapField<java.lang.String, org.tensorflow.framework.AttrValue>
    internalGetAttr() {
      if (attr_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttrDefaultEntryHolder.defaultEntry);
     }
      return attr_;
    }
    /**
     * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
     *
     * <pre>
     * Attrs.
     * 'attr' maps names defined by 'func's attr defs to attr values.
     * attr values may have placeholders which are substituted
     * recursively by concrete values when this node is instantiated.
     * These placeholders must name an attr listed in the FunctionDef's
     * signature.
     * </pre>
     */

    public java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue> getAttr() {
      return internalGetAttr().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ret_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, ret_.getRaw(i));
      }
      if (!getOpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, op_);
      }
      for (int i = 0; i < arg_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, arg_.getRaw(i));
      }
      for (int i = 0; i < dep_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, dep_.getRaw(i));
      }
      for (java.util.Map.Entry<java.lang.String, org.tensorflow.framework.AttrValue> entry
           : internalGetAttr().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.framework.AttrValue>
        attr = AttrDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(5, attr);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ret_.size(); i++) {
          dataSize += computeStringSizeNoTag(ret_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRetList().size();
      }
      if (!getOpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, op_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arg_.size(); i++) {
          dataSize += computeStringSizeNoTag(arg_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getArgList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dep_.size(); i++) {
          dataSize += computeStringSizeNoTag(dep_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDepList().size();
      }
      for (java.util.Map.Entry<java.lang.String, org.tensorflow.framework.AttrValue> entry
           : internalGetAttr().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.framework.AttrValue>
        attr = AttrDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, attr);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tensorflow.framework.FunctionDef.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tensorflow.framework.FunctionDef.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.FunctionDef.Node}
     *
     * <pre>
     * A node is a multi-value assignment:
     *   (ret[0], ret[1], ...) = func(arg[0], arg[1], ...)
     * By convention, "func" is resolved by consulting with a user-defined
     * library first. If not resolved, "func" is assumed to be a builtin op.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.FunctionDef.Node)
        org.tensorflow.framework.FunctionDef.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_Node_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAttr();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAttr();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tensorflow.framework.FunctionDef.Node.class, org.tensorflow.framework.FunctionDef.Node.Builder.class);
      }

      // Construct using org.tensorflow.framework.FunctionDef.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ret_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = "";

        arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        dep_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableAttr().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_Node_descriptor;
      }

      public org.tensorflow.framework.FunctionDef.Node getDefaultInstanceForType() {
        return org.tensorflow.framework.FunctionDef.Node.getDefaultInstance();
      }

      public org.tensorflow.framework.FunctionDef.Node build() {
        org.tensorflow.framework.FunctionDef.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tensorflow.framework.FunctionDef.Node buildPartial() {
        org.tensorflow.framework.FunctionDef.Node result = new org.tensorflow.framework.FunctionDef.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ret_ = ret_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ret_ = ret_;
        result.op_ = op_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          arg_ = arg_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.arg_ = arg_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          dep_ = dep_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.dep_ = dep_;
        result.attr_ = internalGetAttr();
        result.attr_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tensorflow.framework.FunctionDef.Node) {
          return mergeFrom((org.tensorflow.framework.FunctionDef.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tensorflow.framework.FunctionDef.Node other) {
        if (other == org.tensorflow.framework.FunctionDef.Node.getDefaultInstance()) return this;
        if (!other.ret_.isEmpty()) {
          if (ret_.isEmpty()) {
            ret_ = other.ret_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRetIsMutable();
            ret_.addAll(other.ret_);
          }
          onChanged();
        }
        if (!other.getOp().isEmpty()) {
          op_ = other.op_;
          onChanged();
        }
        if (!other.arg_.isEmpty()) {
          if (arg_.isEmpty()) {
            arg_ = other.arg_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureArgIsMutable();
            arg_.addAll(other.arg_);
          }
          onChanged();
        }
        if (!other.dep_.isEmpty()) {
          if (dep_.isEmpty()) {
            dep_ = other.dep_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDepIsMutable();
            dep_.addAll(other.dep_);
          }
          onChanged();
        }
        internalGetMutableAttr().mergeFrom(
            other.internalGetAttr());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tensorflow.framework.FunctionDef.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tensorflow.framework.FunctionDef.Node) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList ret_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRetIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ret_ = new com.google.protobuf.LazyStringArrayList(ret_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getRetList() {
        return ret_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public int getRetCount() {
        return ret_.size();
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public java.lang.String getRet(int index) {
        return ret_.get(index);
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRetBytes(int index) {
        return ret_.getByteString(index);
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public Builder setRet(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRetIsMutable();
        ret_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public Builder addRet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRetIsMutable();
        ret_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public Builder addAllRet(
          java.lang.Iterable<java.lang.String> values) {
        ensureRetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ret_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public Builder clearRet() {
        ret_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ret = 1;</code>
       *
       * <pre>
       * This node produces multiple outputs. They are named ret[0],
       * ret[1], ..., etc.
       * REQUIRES: function.node.ret[*] are unique across all nodes.
       * REQUIRES: ret.size == func/op def's number of output args.
       * </pre>
       */
      public Builder addRetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRetIsMutable();
        ret_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object op_ = "";
      /**
       * <code>optional string op = 2;</code>
       *
       * <pre>
       * The op/function name.
       * </pre>
       */
      public java.lang.String getOp() {
        java.lang.Object ref = op_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          op_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string op = 2;</code>
       *
       * <pre>
       * The op/function name.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOpBytes() {
        java.lang.Object ref = op_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          op_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string op = 2;</code>
       *
       * <pre>
       * The op/function name.
       * </pre>
       */
      public Builder setOp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string op = 2;</code>
       *
       * <pre>
       * The op/function name.
       * </pre>
       */
      public Builder clearOp() {
        
        op_ = getDefaultInstance().getOp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string op = 2;</code>
       *
       * <pre>
       * The op/function name.
       * </pre>
       */
      public Builder setOpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        op_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          arg_ = new com.google.protobuf.LazyStringArrayList(arg_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getArgList() {
        return arg_.getUnmodifiableView();
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public int getArgCount() {
        return arg_.size();
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public java.lang.String getArg(int index) {
        return arg_.get(index);
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getArgBytes(int index) {
        return arg_.getByteString(index);
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public Builder setArg(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgIsMutable();
        arg_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public Builder addArg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgIsMutable();
        arg_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public Builder addAllArg(
          java.lang.Iterable<java.lang.String> values) {
        ensureArgIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arg_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public Builder clearArg() {
        arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string arg = 3;</code>
       *
       * <pre>
       * Arguments passed to this func/op.
       * arg[i] must be either one of
       * function.signature.input_args[*].name or one of
       * function.node[*].ret[*].
       * REQUIRES: arg.size == func/op def's number of input args.
       * </pre>
       */
      public Builder addArgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureArgIsMutable();
        arg_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList dep_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDepIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          dep_ = new com.google.protobuf.LazyStringArrayList(dep_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getDepList() {
        return dep_.getUnmodifiableView();
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public int getDepCount() {
        return dep_.size();
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public java.lang.String getDep(int index) {
        return dep_.get(index);
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDepBytes(int index) {
        return dep_.getByteString(index);
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public Builder setDep(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDepIsMutable();
        dep_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public Builder addDep(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDepIsMutable();
        dep_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public Builder addAllDep(
          java.lang.Iterable<java.lang.String> values) {
        ensureDepIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dep_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public Builder clearDep() {
        dep_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dep = 4;</code>
       *
       * <pre>
       * Control dependencies.
       * dep[i] must be one of function.node[*].ret[*] or one of
       * function.signature.input_args[*].name.
       * </pre>
       */
      public Builder addDepBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDepIsMutable();
        dep_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, org.tensorflow.framework.AttrValue> attr_;
      private com.google.protobuf.MapField<java.lang.String, org.tensorflow.framework.AttrValue>
      internalGetAttr() {
        if (attr_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttrDefaultEntryHolder.defaultEntry);
       }
        return attr_;
      }
      private com.google.protobuf.MapField<java.lang.String, org.tensorflow.framework.AttrValue>
      internalGetMutableAttr() {
        onChanged();;
        if (attr_ == null) {
          attr_ = com.google.protobuf.MapField.newMapField(
              AttrDefaultEntryHolder.defaultEntry);
        }
        if (!attr_.isMutable()) {
          attr_ = attr_.copy();
        }
        return attr_;
      }
      /**
       * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
       *
       * <pre>
       * Attrs.
       * 'attr' maps names defined by 'func's attr defs to attr values.
       * attr values may have placeholders which are substituted
       * recursively by concrete values when this node is instantiated.
       * These placeholders must name an attr listed in the FunctionDef's
       * signature.
       * </pre>
       */
      public java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue> getAttr() {
        return internalGetAttr().getMap();
      }
      /**
       * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
       *
       * <pre>
       * Attrs.
       * 'attr' maps names defined by 'func's attr defs to attr values.
       * attr values may have placeholders which are substituted
       * recursively by concrete values when this node is instantiated.
       * These placeholders must name an attr listed in the FunctionDef's
       * signature.
       * </pre>
       */
      public java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue>
      getMutableAttr() {
        return internalGetMutableAttr().getMutableMap();
      }
      /**
       * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
       *
       * <pre>
       * Attrs.
       * 'attr' maps names defined by 'func's attr defs to attr values.
       * attr values may have placeholders which are substituted
       * recursively by concrete values when this node is instantiated.
       * These placeholders must name an attr listed in the FunctionDef's
       * signature.
       * </pre>
       */
      public Builder putAllAttr(
          java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue> values) {
        getMutableAttr().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.FunctionDef.Node)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.FunctionDef.Node)
    private static final org.tensorflow.framework.FunctionDef.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tensorflow.framework.FunctionDef.Node();
    }

    public static org.tensorflow.framework.FunctionDef.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Node(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    public org.tensorflow.framework.FunctionDef.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int SIGNATURE_FIELD_NUMBER = 1;
  private org.tensorflow.framework.OpDef signature_;
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  public boolean hasSignature() {
    return signature_ != null;
  }
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  public org.tensorflow.framework.OpDef getSignature() {
    return signature_ == null ? org.tensorflow.framework.OpDef.getDefaultInstance() : signature_;
  }
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  public org.tensorflow.framework.OpDefOrBuilder getSignatureOrBuilder() {
    return getSignature();
  }

  public static final int NODE_FIELD_NUMBER = 2;
  private java.util.List<org.tensorflow.framework.FunctionDef.Node> node_;
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  public java.util.List<org.tensorflow.framework.FunctionDef.Node> getNodeList() {
    return node_;
  }
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  public java.util.List<? extends org.tensorflow.framework.FunctionDef.NodeOrBuilder> 
      getNodeOrBuilderList() {
    return node_;
  }
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  public int getNodeCount() {
    return node_.size();
  }
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  public org.tensorflow.framework.FunctionDef.Node getNode(int index) {
    return node_.get(index);
  }
  /**
   * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
   *
   * <pre>
   * The body of the function.
   * </pre>
   */
  public org.tensorflow.framework.FunctionDef.NodeOrBuilder getNodeOrBuilder(
      int index) {
    return node_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (signature_ != null) {
      output.writeMessage(1, getSignature());
    }
    for (int i = 0; i < node_.size(); i++) {
      output.writeMessage(2, node_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (signature_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSignature());
    }
    for (int i = 0; i < node_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, node_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.tensorflow.framework.FunctionDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.FunctionDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.FunctionDef}
   *
   * <pre>
   * A function can be instantiated when the runtime can bind every attr
   * with a value. When a GraphDef has a call to a function, it must
   * have binding for every attr defined in the signature.
   * TODO(zhifengc):
   *   * device spec, etc.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.FunctionDef)
      org.tensorflow.framework.FunctionDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.FunctionDef.class, org.tensorflow.framework.FunctionDef.Builder.class);
    }

    // Construct using org.tensorflow.framework.FunctionDef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getNodeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (signatureBuilder_ == null) {
        signature_ = null;
      } else {
        signature_ = null;
        signatureBuilder_ = null;
      }
      if (nodeBuilder_ == null) {
        node_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        nodeBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_descriptor;
    }

    public org.tensorflow.framework.FunctionDef getDefaultInstanceForType() {
      return org.tensorflow.framework.FunctionDef.getDefaultInstance();
    }

    public org.tensorflow.framework.FunctionDef build() {
      org.tensorflow.framework.FunctionDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.FunctionDef buildPartial() {
      org.tensorflow.framework.FunctionDef result = new org.tensorflow.framework.FunctionDef(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (signatureBuilder_ == null) {
        result.signature_ = signature_;
      } else {
        result.signature_ = signatureBuilder_.build();
      }
      if (nodeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          node_ = java.util.Collections.unmodifiableList(node_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.node_ = node_;
      } else {
        result.node_ = nodeBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.FunctionDef) {
        return mergeFrom((org.tensorflow.framework.FunctionDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.FunctionDef other) {
      if (other == org.tensorflow.framework.FunctionDef.getDefaultInstance()) return this;
      if (other.hasSignature()) {
        mergeSignature(other.getSignature());
      }
      if (nodeBuilder_ == null) {
        if (!other.node_.isEmpty()) {
          if (node_.isEmpty()) {
            node_ = other.node_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNodeIsMutable();
            node_.addAll(other.node_);
          }
          onChanged();
        }
      } else {
        if (!other.node_.isEmpty()) {
          if (nodeBuilder_.isEmpty()) {
            nodeBuilder_.dispose();
            nodeBuilder_ = null;
            node_ = other.node_;
            bitField0_ = (bitField0_ & ~0x00000002);
            nodeBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNodeFieldBuilder() : null;
          } else {
            nodeBuilder_.addAllMessages(other.node_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.FunctionDef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.FunctionDef) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.tensorflow.framework.OpDef signature_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        org.tensorflow.framework.OpDef, org.tensorflow.framework.OpDef.Builder, org.tensorflow.framework.OpDefOrBuilder> signatureBuilder_;
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public boolean hasSignature() {
      return signatureBuilder_ != null || signature_ != null;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public org.tensorflow.framework.OpDef getSignature() {
      if (signatureBuilder_ == null) {
        return signature_ == null ? org.tensorflow.framework.OpDef.getDefaultInstance() : signature_;
      } else {
        return signatureBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder setSignature(org.tensorflow.framework.OpDef value) {
      if (signatureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signature_ = value;
        onChanged();
      } else {
        signatureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder setSignature(
        org.tensorflow.framework.OpDef.Builder builderForValue) {
      if (signatureBuilder_ == null) {
        signature_ = builderForValue.build();
        onChanged();
      } else {
        signatureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder mergeSignature(org.tensorflow.framework.OpDef value) {
      if (signatureBuilder_ == null) {
        if (signature_ != null) {
          signature_ =
            org.tensorflow.framework.OpDef.newBuilder(signature_).mergeFrom(value).buildPartial();
        } else {
          signature_ = value;
        }
        onChanged();
      } else {
        signatureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder clearSignature() {
      if (signatureBuilder_ == null) {
        signature_ = null;
        onChanged();
      } else {
        signature_ = null;
        signatureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public org.tensorflow.framework.OpDef.Builder getSignatureBuilder() {
      
      onChanged();
      return getSignatureFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public org.tensorflow.framework.OpDefOrBuilder getSignatureOrBuilder() {
      if (signatureBuilder_ != null) {
        return signatureBuilder_.getMessageOrBuilder();
      } else {
        return signature_ == null ?
            org.tensorflow.framework.OpDef.getDefaultInstance() : signature_;
      }
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.tensorflow.framework.OpDef, org.tensorflow.framework.OpDef.Builder, org.tensorflow.framework.OpDefOrBuilder> 
        getSignatureFieldBuilder() {
      if (signatureBuilder_ == null) {
        signatureBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.tensorflow.framework.OpDef, org.tensorflow.framework.OpDef.Builder, org.tensorflow.framework.OpDefOrBuilder>(
                getSignature(),
                getParentForChildren(),
                isClean());
        signature_ = null;
      }
      return signatureBuilder_;
    }

    private java.util.List<org.tensorflow.framework.FunctionDef.Node> node_ =
      java.util.Collections.emptyList();
    private void ensureNodeIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        node_ = new java.util.ArrayList<org.tensorflow.framework.FunctionDef.Node>(node_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.FunctionDef.Node, org.tensorflow.framework.FunctionDef.Node.Builder, org.tensorflow.framework.FunctionDef.NodeOrBuilder> nodeBuilder_;

    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.FunctionDef.Node> getNodeList() {
      if (nodeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(node_);
      } else {
        return nodeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public int getNodeCount() {
      if (nodeBuilder_ == null) {
        return node_.size();
      } else {
        return nodeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public org.tensorflow.framework.FunctionDef.Node getNode(int index) {
      if (nodeBuilder_ == null) {
        return node_.get(index);
      } else {
        return nodeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder setNode(
        int index, org.tensorflow.framework.FunctionDef.Node value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeIsMutable();
        node_.set(index, value);
        onChanged();
      } else {
        nodeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder setNode(
        int index, org.tensorflow.framework.FunctionDef.Node.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder addNode(org.tensorflow.framework.FunctionDef.Node value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeIsMutable();
        node_.add(value);
        onChanged();
      } else {
        nodeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder addNode(
        int index, org.tensorflow.framework.FunctionDef.Node value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeIsMutable();
        node_.add(index, value);
        onChanged();
      } else {
        nodeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder addNode(
        org.tensorflow.framework.FunctionDef.Node.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.add(builderForValue.build());
        onChanged();
      } else {
        nodeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder addNode(
        int index, org.tensorflow.framework.FunctionDef.Node.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder addAllNode(
        java.lang.Iterable<? extends org.tensorflow.framework.FunctionDef.Node> values) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, node_);
        onChanged();
      } else {
        nodeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder clearNode() {
      if (nodeBuilder_ == null) {
        node_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        nodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public Builder removeNode(int index) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.remove(index);
        onChanged();
      } else {
        nodeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public org.tensorflow.framework.FunctionDef.Node.Builder getNodeBuilder(
        int index) {
      return getNodeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public org.tensorflow.framework.FunctionDef.NodeOrBuilder getNodeOrBuilder(
        int index) {
      if (nodeBuilder_ == null) {
        return node_.get(index);  } else {
        return nodeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public java.util.List<? extends org.tensorflow.framework.FunctionDef.NodeOrBuilder> 
         getNodeOrBuilderList() {
      if (nodeBuilder_ != null) {
        return nodeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(node_);
      }
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public org.tensorflow.framework.FunctionDef.Node.Builder addNodeBuilder() {
      return getNodeFieldBuilder().addBuilder(
          org.tensorflow.framework.FunctionDef.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public org.tensorflow.framework.FunctionDef.Node.Builder addNodeBuilder(
        int index) {
      return getNodeFieldBuilder().addBuilder(
          index, org.tensorflow.framework.FunctionDef.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.FunctionDef.Node node = 2;</code>
     *
     * <pre>
     * The body of the function.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.FunctionDef.Node.Builder> 
         getNodeBuilderList() {
      return getNodeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.FunctionDef.Node, org.tensorflow.framework.FunctionDef.Node.Builder, org.tensorflow.framework.FunctionDef.NodeOrBuilder> 
        getNodeFieldBuilder() {
      if (nodeBuilder_ == null) {
        nodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.tensorflow.framework.FunctionDef.Node, org.tensorflow.framework.FunctionDef.Node.Builder, org.tensorflow.framework.FunctionDef.NodeOrBuilder>(
                node_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        node_ = null;
      }
      return nodeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.FunctionDef)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.FunctionDef)
  private static final org.tensorflow.framework.FunctionDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.FunctionDef();
  }

  public static org.tensorflow.framework.FunctionDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionDef>
      PARSER = new com.google.protobuf.AbstractParser<FunctionDef>() {
    public FunctionDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new FunctionDef(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<FunctionDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionDef> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.FunctionDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

