// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/function.proto

package org.tensorflow.framework;

public final class FunctionProtos {
  private FunctionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FunctionDefLibrary_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_FunctionDefLibrary_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FunctionDef_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_FunctionDef_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FunctionDef_Node_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_FunctionDef_Node_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_FunctionDef_Node_AttrEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_FunctionDef_Node_AttrEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(tensorflow/core/framework/function.pro" +
      "to\022\ntensorflow\032*tensorflow/core/framewor" +
      "k/attr_value.proto\032&tensorflow/core/fram" +
      "ework/op_def.proto\"?\n\022FunctionDefLibrary" +
      "\022)\n\010function\030\001 \003(\0132\027.tensorflow.Function" +
      "Def\"\225\002\n\013FunctionDef\022$\n\tsignature\030\001 \001(\0132\021" +
      ".tensorflow.OpDef\022*\n\004node\030\002 \003(\0132\034.tensor" +
      "flow.FunctionDef.Node\032\263\001\n\004Node\022\013\n\003ret\030\001 " +
      "\003(\t\022\n\n\002op\030\002 \001(\t\022\013\n\003arg\030\003 \003(\t\022\013\n\003dep\030\004 \003(" +
      "\t\0224\n\004attr\030\005 \003(\0132&.tensorflow.FunctionDef",
      ".Node.AttrEntry\032B\n\tAttrEntry\022\013\n\003key\030\001 \001(" +
      "\t\022$\n\005value\030\002 \001(\0132\025.tensorflow.AttrValue:" +
      "\0028\001B,\n\030org.tensorflow.frameworkB\016Functio" +
      "nProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.AttrValueProtos.getDescriptor(),
          org.tensorflow.framework.OpDefProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_FunctionDefLibrary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_FunctionDefLibrary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_FunctionDefLibrary_descriptor,
        new java.lang.String[] { "Function", });
    internal_static_tensorflow_FunctionDef_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_FunctionDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_FunctionDef_descriptor,
        new java.lang.String[] { "Signature", "Node", });
    internal_static_tensorflow_FunctionDef_Node_descriptor =
      internal_static_tensorflow_FunctionDef_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_FunctionDef_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_FunctionDef_Node_descriptor,
        new java.lang.String[] { "Ret", "Op", "Arg", "Dep", "Attr", });
    internal_static_tensorflow_FunctionDef_Node_AttrEntry_descriptor =
      internal_static_tensorflow_FunctionDef_Node_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_FunctionDef_Node_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_FunctionDef_Node_AttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.tensorflow.framework.AttrValueProtos.getDescriptor();
    org.tensorflow.framework.OpDefProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
