// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/config.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.GPUOptions}
 */
public  final class GPUOptions extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tensorflow.GPUOptions)
    GPUOptionsOrBuilder {
  // Use GPUOptions.newBuilder() to construct.
  private GPUOptions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GPUOptions() {
    perProcessGpuMemoryFraction_ = 0D;
    allocatorType_ = "";
    deferredDeletionBytes_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GPUOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            perProcessGpuMemoryFraction_ = input.readDouble();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            allocatorType_ = s;
            break;
          }
          case 24: {

            deferredDeletionBytes_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.ConfigProtos.internal_static_tensorflow_GPUOptions_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.ConfigProtos.internal_static_tensorflow_GPUOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.GPUOptions.class, org.tensorflow.framework.GPUOptions.Builder.class);
  }

  public static final int PER_PROCESS_GPU_MEMORY_FRACTION_FIELD_NUMBER = 1;
  private double perProcessGpuMemoryFraction_;
  /**
   * <code>optional double per_process_gpu_memory_fraction = 1;</code>
   *
   * <pre>
   * A value between 0 and 1 that indicates what fraction of the
   * available GPU memory to pre-allocate for each process.  1 means
   * to pre-allocate all of the GPU memory, 0.5 means the process
   * allocates ~50% of the available GPU memory.
   * </pre>
   */
  public double getPerProcessGpuMemoryFraction() {
    return perProcessGpuMemoryFraction_;
  }

  public static final int ALLOCATOR_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object allocatorType_;
  /**
   * <code>optional string allocator_type = 2;</code>
   *
   * <pre>
   * The type of GPU allocation strategy to use.
   * Allowed values:
   * "": The empty string (default) uses a system-chosen default
   *     which may change over time.
   * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
   *        version of dlmalloc.
   * </pre>
   */
  public java.lang.String getAllocatorType() {
    java.lang.Object ref = allocatorType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      allocatorType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string allocator_type = 2;</code>
   *
   * <pre>
   * The type of GPU allocation strategy to use.
   * Allowed values:
   * "": The empty string (default) uses a system-chosen default
   *     which may change over time.
   * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
   *        version of dlmalloc.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAllocatorTypeBytes() {
    java.lang.Object ref = allocatorType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      allocatorType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFERRED_DELETION_BYTES_FIELD_NUMBER = 3;
  private long deferredDeletionBytes_;
  /**
   * <code>optional int64 deferred_deletion_bytes = 3;</code>
   *
   * <pre>
   * Delay deletion of up to this many bytes to reduce the number of
   * interactions with gpu driver code.  If 0, the system chooses
   * a reasonable default (several MBs).
   * </pre>
   */
  public long getDeferredDeletionBytes() {
    return deferredDeletionBytes_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (perProcessGpuMemoryFraction_ != 0D) {
      output.writeDouble(1, perProcessGpuMemoryFraction_);
    }
    if (!getAllocatorTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, allocatorType_);
    }
    if (deferredDeletionBytes_ != 0L) {
      output.writeInt64(3, deferredDeletionBytes_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (perProcessGpuMemoryFraction_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, perProcessGpuMemoryFraction_);
    }
    if (!getAllocatorTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, allocatorType_);
    }
    if (deferredDeletionBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, deferredDeletionBytes_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.tensorflow.framework.GPUOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.GPUOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.tensorflow.framework.GPUOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.GPUOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.GPUOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.GPUOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.GPUOptions)
      org.tensorflow.framework.GPUOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.ConfigProtos.internal_static_tensorflow_GPUOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.ConfigProtos.internal_static_tensorflow_GPUOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.GPUOptions.class, org.tensorflow.framework.GPUOptions.Builder.class);
    }

    // Construct using org.tensorflow.framework.GPUOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      perProcessGpuMemoryFraction_ = 0D;

      allocatorType_ = "";

      deferredDeletionBytes_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.ConfigProtos.internal_static_tensorflow_GPUOptions_descriptor;
    }

    public org.tensorflow.framework.GPUOptions getDefaultInstanceForType() {
      return org.tensorflow.framework.GPUOptions.getDefaultInstance();
    }

    public org.tensorflow.framework.GPUOptions build() {
      org.tensorflow.framework.GPUOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.GPUOptions buildPartial() {
      org.tensorflow.framework.GPUOptions result = new org.tensorflow.framework.GPUOptions(this);
      result.perProcessGpuMemoryFraction_ = perProcessGpuMemoryFraction_;
      result.allocatorType_ = allocatorType_;
      result.deferredDeletionBytes_ = deferredDeletionBytes_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.GPUOptions) {
        return mergeFrom((org.tensorflow.framework.GPUOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.GPUOptions other) {
      if (other == org.tensorflow.framework.GPUOptions.getDefaultInstance()) return this;
      if (other.getPerProcessGpuMemoryFraction() != 0D) {
        setPerProcessGpuMemoryFraction(other.getPerProcessGpuMemoryFraction());
      }
      if (!other.getAllocatorType().isEmpty()) {
        allocatorType_ = other.allocatorType_;
        onChanged();
      }
      if (other.getDeferredDeletionBytes() != 0L) {
        setDeferredDeletionBytes(other.getDeferredDeletionBytes());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.GPUOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.GPUOptions) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double perProcessGpuMemoryFraction_ ;
    /**
     * <code>optional double per_process_gpu_memory_fraction = 1;</code>
     *
     * <pre>
     * A value between 0 and 1 that indicates what fraction of the
     * available GPU memory to pre-allocate for each process.  1 means
     * to pre-allocate all of the GPU memory, 0.5 means the process
     * allocates ~50% of the available GPU memory.
     * </pre>
     */
    public double getPerProcessGpuMemoryFraction() {
      return perProcessGpuMemoryFraction_;
    }
    /**
     * <code>optional double per_process_gpu_memory_fraction = 1;</code>
     *
     * <pre>
     * A value between 0 and 1 that indicates what fraction of the
     * available GPU memory to pre-allocate for each process.  1 means
     * to pre-allocate all of the GPU memory, 0.5 means the process
     * allocates ~50% of the available GPU memory.
     * </pre>
     */
    public Builder setPerProcessGpuMemoryFraction(double value) {
      
      perProcessGpuMemoryFraction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double per_process_gpu_memory_fraction = 1;</code>
     *
     * <pre>
     * A value between 0 and 1 that indicates what fraction of the
     * available GPU memory to pre-allocate for each process.  1 means
     * to pre-allocate all of the GPU memory, 0.5 means the process
     * allocates ~50% of the available GPU memory.
     * </pre>
     */
    public Builder clearPerProcessGpuMemoryFraction() {
      
      perProcessGpuMemoryFraction_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object allocatorType_ = "";
    /**
     * <code>optional string allocator_type = 2;</code>
     *
     * <pre>
     * The type of GPU allocation strategy to use.
     * Allowed values:
     * "": The empty string (default) uses a system-chosen default
     *     which may change over time.
     * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
     *        version of dlmalloc.
     * </pre>
     */
    public java.lang.String getAllocatorType() {
      java.lang.Object ref = allocatorType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allocatorType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string allocator_type = 2;</code>
     *
     * <pre>
     * The type of GPU allocation strategy to use.
     * Allowed values:
     * "": The empty string (default) uses a system-chosen default
     *     which may change over time.
     * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
     *        version of dlmalloc.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAllocatorTypeBytes() {
      java.lang.Object ref = allocatorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allocatorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string allocator_type = 2;</code>
     *
     * <pre>
     * The type of GPU allocation strategy to use.
     * Allowed values:
     * "": The empty string (default) uses a system-chosen default
     *     which may change over time.
     * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
     *        version of dlmalloc.
     * </pre>
     */
    public Builder setAllocatorType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      allocatorType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string allocator_type = 2;</code>
     *
     * <pre>
     * The type of GPU allocation strategy to use.
     * Allowed values:
     * "": The empty string (default) uses a system-chosen default
     *     which may change over time.
     * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
     *        version of dlmalloc.
     * </pre>
     */
    public Builder clearAllocatorType() {
      
      allocatorType_ = getDefaultInstance().getAllocatorType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string allocator_type = 2;</code>
     *
     * <pre>
     * The type of GPU allocation strategy to use.
     * Allowed values:
     * "": The empty string (default) uses a system-chosen default
     *     which may change over time.
     * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
     *        version of dlmalloc.
     * </pre>
     */
    public Builder setAllocatorTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      allocatorType_ = value;
      onChanged();
      return this;
    }

    private long deferredDeletionBytes_ ;
    /**
     * <code>optional int64 deferred_deletion_bytes = 3;</code>
     *
     * <pre>
     * Delay deletion of up to this many bytes to reduce the number of
     * interactions with gpu driver code.  If 0, the system chooses
     * a reasonable default (several MBs).
     * </pre>
     */
    public long getDeferredDeletionBytes() {
      return deferredDeletionBytes_;
    }
    /**
     * <code>optional int64 deferred_deletion_bytes = 3;</code>
     *
     * <pre>
     * Delay deletion of up to this many bytes to reduce the number of
     * interactions with gpu driver code.  If 0, the system chooses
     * a reasonable default (several MBs).
     * </pre>
     */
    public Builder setDeferredDeletionBytes(long value) {
      
      deferredDeletionBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 deferred_deletion_bytes = 3;</code>
     *
     * <pre>
     * Delay deletion of up to this many bytes to reduce the number of
     * interactions with gpu driver code.  If 0, the system chooses
     * a reasonable default (several MBs).
     * </pre>
     */
    public Builder clearDeferredDeletionBytes() {
      
      deferredDeletionBytes_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.GPUOptions)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.GPUOptions)
  private static final org.tensorflow.framework.GPUOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.GPUOptions();
  }

  public static org.tensorflow.framework.GPUOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GPUOptions>
      PARSER = new com.google.protobuf.AbstractParser<GPUOptions>() {
    public GPUOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new GPUOptions(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<GPUOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GPUOptions> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.GPUOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

