// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/config.proto

package org.tensorflow.framework;

public interface GPUOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GPUOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double per_process_gpu_memory_fraction = 1;</code>
   *
   * <pre>
   * A value between 0 and 1 that indicates what fraction of the
   * available GPU memory to pre-allocate for each process.  1 means
   * to pre-allocate all of the GPU memory, 0.5 means the process
   * allocates ~50% of the available GPU memory.
   * </pre>
   */
  double getPerProcessGpuMemoryFraction();

  /**
   * <code>optional string allocator_type = 2;</code>
   *
   * <pre>
   * The type of GPU allocation strategy to use.
   * Allowed values:
   * "": The empty string (default) uses a system-chosen default
   *     which may change over time.
   * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
   *        version of dlmalloc.
   * </pre>
   */
  java.lang.String getAllocatorType();
  /**
   * <code>optional string allocator_type = 2;</code>
   *
   * <pre>
   * The type of GPU allocation strategy to use.
   * Allowed values:
   * "": The empty string (default) uses a system-chosen default
   *     which may change over time.
   * "BFC": A "Best-fit with coalescing" algorithm, simplified from a
   *        version of dlmalloc.
   * </pre>
   */
  com.google.protobuf.ByteString
      getAllocatorTypeBytes();

  /**
   * <code>optional int64 deferred_deletion_bytes = 3;</code>
   *
   * <pre>
   * Delay deletion of up to this many bytes to reduce the number of
   * interactions with gpu driver code.  If 0, the system chooses
   * a reasonable default (several MBs).
   * </pre>
   */
  long getDeferredDeletionBytes();
}
