// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/config.proto

package org.tensorflow.framework;

public interface GraphOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GraphOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool enable_recv_scheduling = 2;</code>
   *
   * <pre>
   * If true, use control flow to schedule the activation of Recv nodes.
   * (Currently ignored.)
   * </pre>
   */
  boolean getEnableRecvScheduling();

  /**
   * <code>optional .tensorflow.OptimizerOptions optimizer_options = 3;</code>
   *
   * <pre>
   * Options controlling how graph is optimized.
   * </pre>
   */
  boolean hasOptimizerOptions();
  /**
   * <code>optional .tensorflow.OptimizerOptions optimizer_options = 3;</code>
   *
   * <pre>
   * Options controlling how graph is optimized.
   * </pre>
   */
  org.tensorflow.framework.OptimizerOptions getOptimizerOptions();
  /**
   * <code>optional .tensorflow.OptimizerOptions optimizer_options = 3;</code>
   *
   * <pre>
   * Options controlling how graph is optimized.
   * </pre>
   */
  org.tensorflow.framework.OptimizerOptionsOrBuilder getOptimizerOptionsOrBuilder();
}
