// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/kernel_def.proto

package org.tensorflow.framework;

public interface KernelDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.KernelDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string op = 1;</code>
   *
   * <pre>
   * Must match the name of an Op.
   * </pre>
   */
  java.lang.String getOp();
  /**
   * <code>optional string op = 1;</code>
   *
   * <pre>
   * Must match the name of an Op.
   * </pre>
   */
  com.google.protobuf.ByteString
      getOpBytes();

  /**
   * <code>optional string device_type = 2;</code>
   *
   * <pre>
   * Type of device this kernel runs on.
   * </pre>
   */
  java.lang.String getDeviceType();
  /**
   * <code>optional string device_type = 2;</code>
   *
   * <pre>
   * Type of device this kernel runs on.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
   */
  java.util.List<org.tensorflow.framework.KernelDef.AttrConstraint> 
      getConstraintList();
  /**
   * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
   */
  org.tensorflow.framework.KernelDef.AttrConstraint getConstraint(int index);
  /**
   * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
   */
  int getConstraintCount();
  /**
   * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
   */
  java.util.List<? extends org.tensorflow.framework.KernelDef.AttrConstraintOrBuilder> 
      getConstraintOrBuilderList();
  /**
   * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
   */
  org.tensorflow.framework.KernelDef.AttrConstraintOrBuilder getConstraintOrBuilder(
      int index);

  /**
   * <code>repeated string host_memory_arg = 4;</code>
   *
   * <pre>
   * Names of the Op's input_/output_args that reside in host memory
   * instead of device memory.
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getHostMemoryArgList();
  /**
   * <code>repeated string host_memory_arg = 4;</code>
   *
   * <pre>
   * Names of the Op's input_/output_args that reside in host memory
   * instead of device memory.
   * </pre>
   */
  int getHostMemoryArgCount();
  /**
   * <code>repeated string host_memory_arg = 4;</code>
   *
   * <pre>
   * Names of the Op's input_/output_args that reside in host memory
   * instead of device memory.
   * </pre>
   */
  java.lang.String getHostMemoryArg(int index);
  /**
   * <code>repeated string host_memory_arg = 4;</code>
   *
   * <pre>
   * Names of the Op's input_/output_args that reside in host memory
   * instead of device memory.
   * </pre>
   */
  com.google.protobuf.ByteString
      getHostMemoryArgBytes(int index);

  /**
   * <code>optional string label = 5;</code>
   *
   * <pre>
   * This allows experimental kernels to be registered for an op that
   * won't be used unless the user specifies a "_kernel" attr with
   * value matching this.
   * </pre>
   */
  java.lang.String getLabel();
  /**
   * <code>optional string label = 5;</code>
   *
   * <pre>
   * This allows experimental kernels to be registered for an op that
   * won't be used unless the user specifies a "_kernel" attr with
   * value matching this.
   * </pre>
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
