// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/config.proto

package org.tensorflow.framework;

public interface OptimizerOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.OptimizerOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool do_common_subexpression_elimination = 1;</code>
   *
   * <pre>
   * If true, optimize the graph using common subexpression elimination.
   * </pre>
   */
  boolean getDoCommonSubexpressionElimination();

  /**
   * <code>optional bool do_constant_folding = 2;</code>
   *
   * <pre>
   * If true, perform constant folding optimization on the graph.
   * </pre>
   */
  boolean getDoConstantFolding();

  /**
   * <code>optional bool do_function_inlining = 4;</code>
   *
   * <pre>
   * If true, perform function inlining on the graph.
   * </pre>
   */
  boolean getDoFunctionInlining();

  /**
   * <code>optional .tensorflow.OptimizerOptions.Level opt_level = 3;</code>
   */
  int getOptLevelValue();
  /**
   * <code>optional .tensorflow.OptimizerOptions.Level opt_level = 3;</code>
   */
  org.tensorflow.framework.OptimizerOptions.Level getOptLevel();
}
