// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/variable.proto

package org.tensorflow.framework;

public interface SaveSliceInfoDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.SaveSliceInfoDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string full_name = 1;</code>
   *
   * <pre>
   * Name of the full variable of which this is a slice.
   * </pre>
   */
  java.lang.String getFullName();
  /**
   * <code>optional string full_name = 1;</code>
   *
   * <pre>
   * Name of the full variable of which this is a slice.
   * </pre>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>repeated int32 full_shape = 2;</code>
   *
   * <pre>
   * Shape of the full variable.
   * </pre>
   */
  java.util.List<java.lang.Integer> getFullShapeList();
  /**
   * <code>repeated int32 full_shape = 2;</code>
   *
   * <pre>
   * Shape of the full variable.
   * </pre>
   */
  int getFullShapeCount();
  /**
   * <code>repeated int32 full_shape = 2;</code>
   *
   * <pre>
   * Shape of the full variable.
   * </pre>
   */
  int getFullShape(int index);

  /**
   * <code>repeated int32 var_offset = 3;</code>
   *
   * <pre>
   * Offset of this variable into the full variable.
   * </pre>
   */
  java.util.List<java.lang.Integer> getVarOffsetList();
  /**
   * <code>repeated int32 var_offset = 3;</code>
   *
   * <pre>
   * Offset of this variable into the full variable.
   * </pre>
   */
  int getVarOffsetCount();
  /**
   * <code>repeated int32 var_offset = 3;</code>
   *
   * <pre>
   * Offset of this variable into the full variable.
   * </pre>
   */
  int getVarOffset(int index);

  /**
   * <code>repeated int32 var_shape = 4;</code>
   *
   * <pre>
   * Shape of this variable.
   * </pre>
   */
  java.util.List<java.lang.Integer> getVarShapeList();
  /**
   * <code>repeated int32 var_shape = 4;</code>
   *
   * <pre>
   * Shape of this variable.
   * </pre>
   */
  int getVarShapeCount();
  /**
   * <code>repeated int32 var_shape = 4;</code>
   *
   * <pre>
   * Shape of this variable.
   * </pre>
   */
  int getVarShape(int index);
}
