// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor_slice.proto

package org.tensorflow.framework;

public interface TensorSliceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.TensorSliceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.TensorSliceProto.Extent extent = 1;</code>
   *
   * <pre>
   * Extent of the slice in all tensor dimensions.
   * Must have one entry for each of the dimension of the tensor that this
   * slice belongs to.  The order of sizes is the same as the order of
   * dimensions in the TensorShape.
   * </pre>
   */
  java.util.List<org.tensorflow.framework.TensorSliceProto.Extent> 
      getExtentList();
  /**
   * <code>repeated .tensorflow.TensorSliceProto.Extent extent = 1;</code>
   *
   * <pre>
   * Extent of the slice in all tensor dimensions.
   * Must have one entry for each of the dimension of the tensor that this
   * slice belongs to.  The order of sizes is the same as the order of
   * dimensions in the TensorShape.
   * </pre>
   */
  org.tensorflow.framework.TensorSliceProto.Extent getExtent(int index);
  /**
   * <code>repeated .tensorflow.TensorSliceProto.Extent extent = 1;</code>
   *
   * <pre>
   * Extent of the slice in all tensor dimensions.
   * Must have one entry for each of the dimension of the tensor that this
   * slice belongs to.  The order of sizes is the same as the order of
   * dimensions in the TensorShape.
   * </pre>
   */
  int getExtentCount();
  /**
   * <code>repeated .tensorflow.TensorSliceProto.Extent extent = 1;</code>
   *
   * <pre>
   * Extent of the slice in all tensor dimensions.
   * Must have one entry for each of the dimension of the tensor that this
   * slice belongs to.  The order of sizes is the same as the order of
   * dimensions in the TensorShape.
   * </pre>
   */
  java.util.List<? extends org.tensorflow.framework.TensorSliceProto.ExtentOrBuilder> 
      getExtentOrBuilderList();
  /**
   * <code>repeated .tensorflow.TensorSliceProto.Extent extent = 1;</code>
   *
   * <pre>
   * Extent of the slice in all tensor dimensions.
   * Must have one entry for each of the dimension of the tensor that this
   * slice belongs to.  The order of sizes is the same as the order of
   * dimensions in the TensorShape.
   * </pre>
   */
  org.tensorflow.framework.TensorSliceProto.ExtentOrBuilder getExtentOrBuilder(
      int index);
}
