// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor_shape.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.TensorShapeProto}
 *
 * <pre>
 * Dimensions of a tensor.
 * </pre>
 */
public  final class TensorShapeProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tensorflow.TensorShapeProto)
    TensorShapeProtoOrBuilder {
  // Use TensorShapeProto.newBuilder() to construct.
  private TensorShapeProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TensorShapeProto() {
    dim_ = java.util.Collections.emptyList();
    unknownRank_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TensorShapeProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              dim_ = new java.util.ArrayList<org.tensorflow.framework.TensorShapeProto.Dim>();
              mutable_bitField0_ |= 0x00000001;
            }
            dim_.add(input.readMessage(org.tensorflow.framework.TensorShapeProto.Dim.parser(), extensionRegistry));
            break;
          }
          case 24: {

            unknownRank_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        dim_ = java.util.Collections.unmodifiableList(dim_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.TensorShapeProto.class, org.tensorflow.framework.TensorShapeProto.Builder.class);
  }

  public interface DimOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.TensorShapeProto.Dim)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 size = 1;</code>
     *
     * <pre>
     * Size of the tensor in that dimension.
     * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     * </pre>
     */
    long getSize();

    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code tensorflow.TensorShapeProto.Dim}
   *
   * <pre>
   * One dimension of the tensor.
   * </pre>
   */
  public  static final class Dim extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.TensorShapeProto.Dim)
      DimOrBuilder {
    // Use Dim.newBuilder() to construct.
    private Dim(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Dim() {
      size_ = 0L;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Dim(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              size_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_Dim_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_Dim_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.TensorShapeProto.Dim.class, org.tensorflow.framework.TensorShapeProto.Dim.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private long size_;
    /**
     * <code>optional int64 size = 1;</code>
     *
     * <pre>
     * Size of the tensor in that dimension.
     * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     * </pre>
     */
    public long getSize() {
      return size_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Optional name of the tensor dimension.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0L) {
        output.writeInt64(1, size_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, size_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tensorflow.framework.TensorShapeProto.Dim parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tensorflow.framework.TensorShapeProto.Dim prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.TensorShapeProto.Dim}
     *
     * <pre>
     * One dimension of the tensor.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.TensorShapeProto.Dim)
        org.tensorflow.framework.TensorShapeProto.DimOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_Dim_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_Dim_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tensorflow.framework.TensorShapeProto.Dim.class, org.tensorflow.framework.TensorShapeProto.Dim.Builder.class);
      }

      // Construct using org.tensorflow.framework.TensorShapeProto.Dim.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        size_ = 0L;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_Dim_descriptor;
      }

      public org.tensorflow.framework.TensorShapeProto.Dim getDefaultInstanceForType() {
        return org.tensorflow.framework.TensorShapeProto.Dim.getDefaultInstance();
      }

      public org.tensorflow.framework.TensorShapeProto.Dim build() {
        org.tensorflow.framework.TensorShapeProto.Dim result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tensorflow.framework.TensorShapeProto.Dim buildPartial() {
        org.tensorflow.framework.TensorShapeProto.Dim result = new org.tensorflow.framework.TensorShapeProto.Dim(this);
        result.size_ = size_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tensorflow.framework.TensorShapeProto.Dim) {
          return mergeFrom((org.tensorflow.framework.TensorShapeProto.Dim)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tensorflow.framework.TensorShapeProto.Dim other) {
        if (other == org.tensorflow.framework.TensorShapeProto.Dim.getDefaultInstance()) return this;
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tensorflow.framework.TensorShapeProto.Dim parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tensorflow.framework.TensorShapeProto.Dim) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long size_ ;
      /**
       * <code>optional int64 size = 1;</code>
       *
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>optional int64 size = 1;</code>
       *
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       */
      public Builder setSize(long value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 size = 1;</code>
       *
       * <pre>
       * Size of the tensor in that dimension.
       * This value must be &gt;= -1, but values of -1 are reserved for "unknown"
       * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
       * that work with TensorShapeProto may fail at runtime when deserializing
       * a TensorShapeProto containing a dim value of -1.
       * </pre>
       */
      public Builder clearSize() {
        
        size_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Optional name of the tensor dimension.
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.TensorShapeProto.Dim)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.TensorShapeProto.Dim)
    private static final org.tensorflow.framework.TensorShapeProto.Dim DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tensorflow.framework.TensorShapeProto.Dim();
    }

    public static org.tensorflow.framework.TensorShapeProto.Dim getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dim>
        PARSER = new com.google.protobuf.AbstractParser<Dim>() {
      public Dim parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Dim(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Dim> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dim> getParserForType() {
      return PARSER;
    }

    public org.tensorflow.framework.TensorShapeProto.Dim getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int DIM_FIELD_NUMBER = 2;
  private java.util.List<org.tensorflow.framework.TensorShapeProto.Dim> dim_;
  /**
   * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
   *
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   */
  public java.util.List<org.tensorflow.framework.TensorShapeProto.Dim> getDimList() {
    return dim_;
  }
  /**
   * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
   *
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   */
  public java.util.List<? extends org.tensorflow.framework.TensorShapeProto.DimOrBuilder> 
      getDimOrBuilderList() {
    return dim_;
  }
  /**
   * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
   *
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   */
  public int getDimCount() {
    return dim_.size();
  }
  /**
   * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
   *
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   */
  public org.tensorflow.framework.TensorShapeProto.Dim getDim(int index) {
    return dim_.get(index);
  }
  /**
   * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
   *
   * <pre>
   * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
   * for a 30 x 40 2D tensor.  If an entry has size -1, this
   * corresponds to a dimension of unknown size. The names are
   * optional.
   * The order of entries in "dim" matters: It indicates the layout of the
   * values in the tensor in-memory representation.
   * The first entry in "dim" is the outermost dimension used to layout the
   * values, the last entry is the innermost dimension.  This matches the
   * in-memory layout of RowMajor Eigen tensors.
   * If "dim.size()" &gt; 0, "unknown_rank" must be false.
   * </pre>
   */
  public org.tensorflow.framework.TensorShapeProto.DimOrBuilder getDimOrBuilder(
      int index) {
    return dim_.get(index);
  }

  public static final int UNKNOWN_RANK_FIELD_NUMBER = 3;
  private boolean unknownRank_;
  /**
   * <code>optional bool unknown_rank = 3;</code>
   *
   * <pre>
   * If true, the number of dimensions in the shape is unknown.
   * If true, "dim.size()" must be 0.
   * </pre>
   */
  public boolean getUnknownRank() {
    return unknownRank_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dim_.size(); i++) {
      output.writeMessage(2, dim_.get(i));
    }
    if (unknownRank_ != false) {
      output.writeBool(3, unknownRank_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dim_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, dim_.get(i));
    }
    if (unknownRank_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, unknownRank_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.tensorflow.framework.TensorShapeProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.TensorShapeProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.tensorflow.framework.TensorShapeProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.TensorShapeProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.TensorShapeProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.TensorShapeProto}
   *
   * <pre>
   * Dimensions of a tensor.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.TensorShapeProto)
      org.tensorflow.framework.TensorShapeProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.TensorShapeProto.class, org.tensorflow.framework.TensorShapeProto.Builder.class);
    }

    // Construct using org.tensorflow.framework.TensorShapeProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDimFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (dimBuilder_ == null) {
        dim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dimBuilder_.clear();
      }
      unknownRank_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.TensorShapeProtos.internal_static_tensorflow_TensorShapeProto_descriptor;
    }

    public org.tensorflow.framework.TensorShapeProto getDefaultInstanceForType() {
      return org.tensorflow.framework.TensorShapeProto.getDefaultInstance();
    }

    public org.tensorflow.framework.TensorShapeProto build() {
      org.tensorflow.framework.TensorShapeProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.TensorShapeProto buildPartial() {
      org.tensorflow.framework.TensorShapeProto result = new org.tensorflow.framework.TensorShapeProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (dimBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dim_ = java.util.Collections.unmodifiableList(dim_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dim_ = dim_;
      } else {
        result.dim_ = dimBuilder_.build();
      }
      result.unknownRank_ = unknownRank_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.TensorShapeProto) {
        return mergeFrom((org.tensorflow.framework.TensorShapeProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.TensorShapeProto other) {
      if (other == org.tensorflow.framework.TensorShapeProto.getDefaultInstance()) return this;
      if (dimBuilder_ == null) {
        if (!other.dim_.isEmpty()) {
          if (dim_.isEmpty()) {
            dim_ = other.dim_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDimIsMutable();
            dim_.addAll(other.dim_);
          }
          onChanged();
        }
      } else {
        if (!other.dim_.isEmpty()) {
          if (dimBuilder_.isEmpty()) {
            dimBuilder_.dispose();
            dimBuilder_ = null;
            dim_ = other.dim_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dimBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getDimFieldBuilder() : null;
          } else {
            dimBuilder_.addAllMessages(other.dim_);
          }
        }
      }
      if (other.getUnknownRank() != false) {
        setUnknownRank(other.getUnknownRank());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.TensorShapeProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.TensorShapeProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.tensorflow.framework.TensorShapeProto.Dim> dim_ =
      java.util.Collections.emptyList();
    private void ensureDimIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        dim_ = new java.util.ArrayList<org.tensorflow.framework.TensorShapeProto.Dim>(dim_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.TensorShapeProto.Dim, org.tensorflow.framework.TensorShapeProto.Dim.Builder, org.tensorflow.framework.TensorShapeProto.DimOrBuilder> dimBuilder_;

    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.TensorShapeProto.Dim> getDimList() {
      if (dimBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dim_);
      } else {
        return dimBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public int getDimCount() {
      if (dimBuilder_ == null) {
        return dim_.size();
      } else {
        return dimBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public org.tensorflow.framework.TensorShapeProto.Dim getDim(int index) {
      if (dimBuilder_ == null) {
        return dim_.get(index);
      } else {
        return dimBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder setDim(
        int index, org.tensorflow.framework.TensorShapeProto.Dim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.set(index, value);
        onChanged();
      } else {
        dimBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder setDim(
        int index, org.tensorflow.framework.TensorShapeProto.Dim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.set(index, builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder addDim(org.tensorflow.framework.TensorShapeProto.Dim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.add(value);
        onChanged();
      } else {
        dimBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder addDim(
        int index, org.tensorflow.framework.TensorShapeProto.Dim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.add(index, value);
        onChanged();
      } else {
        dimBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder addDim(
        org.tensorflow.framework.TensorShapeProto.Dim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.add(builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder addDim(
        int index, org.tensorflow.framework.TensorShapeProto.Dim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.add(index, builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder addAllDim(
        java.lang.Iterable<? extends org.tensorflow.framework.TensorShapeProto.Dim> values) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dim_);
        onChanged();
      } else {
        dimBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder clearDim() {
      if (dimBuilder_ == null) {
        dim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dimBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public Builder removeDim(int index) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.remove(index);
        onChanged();
      } else {
        dimBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public org.tensorflow.framework.TensorShapeProto.Dim.Builder getDimBuilder(
        int index) {
      return getDimFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public org.tensorflow.framework.TensorShapeProto.DimOrBuilder getDimOrBuilder(
        int index) {
      if (dimBuilder_ == null) {
        return dim_.get(index);  } else {
        return dimBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public java.util.List<? extends org.tensorflow.framework.TensorShapeProto.DimOrBuilder> 
         getDimOrBuilderList() {
      if (dimBuilder_ != null) {
        return dimBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dim_);
      }
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public org.tensorflow.framework.TensorShapeProto.Dim.Builder addDimBuilder() {
      return getDimFieldBuilder().addBuilder(
          org.tensorflow.framework.TensorShapeProto.Dim.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public org.tensorflow.framework.TensorShapeProto.Dim.Builder addDimBuilder(
        int index) {
      return getDimFieldBuilder().addBuilder(
          index, org.tensorflow.framework.TensorShapeProto.Dim.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.TensorShapeProto.Dim dim = 2;</code>
     *
     * <pre>
     * Dimensions of the tensor, such as {"input", 30}, {"output", 40}
     * for a 30 x 40 2D tensor.  If an entry has size -1, this
     * corresponds to a dimension of unknown size. The names are
     * optional.
     * The order of entries in "dim" matters: It indicates the layout of the
     * values in the tensor in-memory representation.
     * The first entry in "dim" is the outermost dimension used to layout the
     * values, the last entry is the innermost dimension.  This matches the
     * in-memory layout of RowMajor Eigen tensors.
     * If "dim.size()" &gt; 0, "unknown_rank" must be false.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.TensorShapeProto.Dim.Builder> 
         getDimBuilderList() {
      return getDimFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.TensorShapeProto.Dim, org.tensorflow.framework.TensorShapeProto.Dim.Builder, org.tensorflow.framework.TensorShapeProto.DimOrBuilder> 
        getDimFieldBuilder() {
      if (dimBuilder_ == null) {
        dimBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.tensorflow.framework.TensorShapeProto.Dim, org.tensorflow.framework.TensorShapeProto.Dim.Builder, org.tensorflow.framework.TensorShapeProto.DimOrBuilder>(
                dim_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        dim_ = null;
      }
      return dimBuilder_;
    }

    private boolean unknownRank_ ;
    /**
     * <code>optional bool unknown_rank = 3;</code>
     *
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     * If true, "dim.size()" must be 0.
     * </pre>
     */
    public boolean getUnknownRank() {
      return unknownRank_;
    }
    /**
     * <code>optional bool unknown_rank = 3;</code>
     *
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     * If true, "dim.size()" must be 0.
     * </pre>
     */
    public Builder setUnknownRank(boolean value) {
      
      unknownRank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool unknown_rank = 3;</code>
     *
     * <pre>
     * If true, the number of dimensions in the shape is unknown.
     * If true, "dim.size()" must be 0.
     * </pre>
     */
    public Builder clearUnknownRank() {
      
      unknownRank_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.TensorShapeProto)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.TensorShapeProto)
  private static final org.tensorflow.framework.TensorShapeProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.TensorShapeProto();
  }

  public static org.tensorflow.framework.TensorShapeProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TensorShapeProto>
      PARSER = new com.google.protobuf.AbstractParser<TensorShapeProto>() {
    public TensorShapeProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new TensorShapeProto(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<TensorShapeProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TensorShapeProto> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.TensorShapeProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

