// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor_description.proto

package org.tensorflow.framework;

public interface TensorDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.TensorDescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.DataType dtype = 1;</code>
   *
   * <pre>
   * Data type of tensor elements
   * </pre>
   */
  int getDtypeValue();
  /**
   * <code>optional .tensorflow.DataType dtype = 1;</code>
   *
   * <pre>
   * Data type of tensor elements
   * </pre>
   */
  org.tensorflow.framework.DataType getDtype();

  /**
   * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
   *
   * <pre>
   * Shape of the tensor.
   * </pre>
   */
  boolean hasShape();
  /**
   * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
   *
   * <pre>
   * Shape of the tensor.
   * </pre>
   */
  org.tensorflow.framework.TensorShapeProto getShape();
  /**
   * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
   *
   * <pre>
   * Shape of the tensor.
   * </pre>
   */
  org.tensorflow.framework.TensorShapeProtoOrBuilder getShapeOrBuilder();

  /**
   * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
   *
   * <pre>
   * Information about the size and allocator used for the data
   * </pre>
   */
  boolean hasAllocationDescription();
  /**
   * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
   *
   * <pre>
   * Information about the size and allocator used for the data
   * </pre>
   */
  org.tensorflow.framework.AllocationDescription getAllocationDescription();
  /**
   * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
   *
   * <pre>
   * Information about the size and allocator used for the data
   * </pre>
   */
  org.tensorflow.framework.AllocationDescriptionOrBuilder getAllocationDescriptionOrBuilder();
}
