// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/variable.proto

package org.tensorflow.framework;

public interface VariableDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.VariableDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string variable_name = 1;</code>
   *
   * <pre>
   * Name of the variable tensor.
   * </pre>
   */
  java.lang.String getVariableName();
  /**
   * <code>optional string variable_name = 1;</code>
   *
   * <pre>
   * Name of the variable tensor.
   * </pre>
   */
  com.google.protobuf.ByteString
      getVariableNameBytes();

  /**
   * <code>optional string initializer_name = 2;</code>
   *
   * <pre>
   * Name of the initializer op.
   * </pre>
   */
  java.lang.String getInitializerName();
  /**
   * <code>optional string initializer_name = 2;</code>
   *
   * <pre>
   * Name of the initializer op.
   * </pre>
   */
  com.google.protobuf.ByteString
      getInitializerNameBytes();

  /**
   * <code>optional string snapshot_name = 3;</code>
   *
   * <pre>
   * Name of the snapshot tensor.
   * </pre>
   */
  java.lang.String getSnapshotName();
  /**
   * <code>optional string snapshot_name = 3;</code>
   *
   * <pre>
   * Name of the snapshot tensor.
   * </pre>
   */
  com.google.protobuf.ByteString
      getSnapshotNameBytes();

  /**
   * <code>optional .tensorflow.SaveSliceInfoDef save_slice_info_def = 4;</code>
   *
   * <pre>
   * Support for saving variables as slices of a larger variable.
   * </pre>
   */
  boolean hasSaveSliceInfoDef();
  /**
   * <code>optional .tensorflow.SaveSliceInfoDef save_slice_info_def = 4;</code>
   *
   * <pre>
   * Support for saving variables as slices of a larger variable.
   * </pre>
   */
  org.tensorflow.framework.SaveSliceInfoDef getSaveSliceInfoDef();
  /**
   * <code>optional .tensorflow.SaveSliceInfoDef save_slice_info_def = 4;</code>
   *
   * <pre>
   * Support for saving variables as slices of a larger variable.
   * </pre>
   */
  org.tensorflow.framework.SaveSliceInfoDefOrBuilder getSaveSliceInfoDefOrBuilder();
}
