// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/versions.proto

package org.tensorflow.framework;

public interface VersionDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.VersionDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 producer = 1;</code>
   *
   * <pre>
   * The version of the code that produced this data.
   * </pre>
   */
  int getProducer();

  /**
   * <code>optional int32 min_consumer = 2;</code>
   *
   * <pre>
   * Any consumer below this version is not allowed to consume this data.
   * </pre>
   */
  int getMinConsumer();

  /**
   * <code>repeated int32 bad_consumers = 3;</code>
   *
   * <pre>
   * Specific consumer versions which are disallowed (e.g. due to bugs).
   * </pre>
   */
  java.util.List<java.lang.Integer> getBadConsumersList();
  /**
   * <code>repeated int32 bad_consumers = 3;</code>
   *
   * <pre>
   * Specific consumer versions which are disallowed (e.g. due to bugs).
   * </pre>
   */
  int getBadConsumersCount();
  /**
   * <code>repeated int32 bad_consumers = 3;</code>
   *
   * <pre>
   * Specific consumer versions which are disallowed (e.g. due to bugs).
   * </pre>
   */
  int getBadConsumers(int index);
}
